// Generated by Rivet. Do not edit by hand.
#pragma once

#include <cstdint>
#include <exception>
#include <functional>
#include <future>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <variant>
#include <vector>

#include "backend.hpp"

namespace rivet_app {
inline constexpr char kModuleName[] = "backend";
inline constexpr char kEntryName[] = "start";
inline constexpr char kDisplayName[] = "Rivet Taskboard";
inline constexpr char kVersion[] = "0.1.0";
inline constexpr std::int64_t kBuild = 1;
inline constexpr char kIdentifier[] = "dev.rivet.taskboard";
inline constexpr char kReleaseChannel[] = "stable";

enum class TaskStatus { backlog, active, done };

struct BoardTask {
  std::int64_t id;
  std::string title;
  std::string notes;
  TaskStatus status;
};

struct ImportProgress {
  std::int64_t completed;
  std::int64_t total;
  std::string message;
};

template <typename T>
struct Result {
  std::optional<T> value;
  std::exception_ptr error;
  bool succeeded() const noexcept { return value.has_value() && !error; }
  T const& get() const { if (error) std::rethrow_exception(error); if (!value) throw std::runtime_error("Rivet async result has no value"); return *value; }
};

template <>
struct Result<void> {
  std::exception_ptr error;
  bool succeeded() const noexcept { return !error; }
  void get() const { if (error) std::rethrow_exception(error); }
};

namespace detail {
inline rivet::Value encode_String(std::string const& v) { return rivet::Value(v); }
inline rivet::Value encode_Int64(std::int64_t v) { return rivet::Value(v); }
inline rivet::Value encode_TaskStatus(TaskStatus v) { switch (v) { case TaskStatus::backlog: return rivet::Value(std::string("backlog")); case TaskStatus::active: return rivet::Value(std::string("active")); case TaskStatus::done: return rivet::Value(std::string("done")); } throw std::runtime_error("invalid Rivet enum value"); }
inline rivet::Value encode_BoardTask(BoardTask const& v) { rivet::Value::List r; r.reserve(4); r.push_back(encode_Int64(v.id)); r.push_back(encode_String(v.title)); r.push_back(encode_String(v.notes)); r.push_back(encode_TaskStatus(v.status)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Bool(bool v) { return rivet::Value(v); }
inline rivet::Value encode__List_BoardTask_(std::vector<BoardTask> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_BoardTask(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__Optional_BoardTask_(std::optional<BoardTask> const& v) { return v ? encode_BoardTask(*v) : rivet::Value{}; }
inline rivet::Value encode_ImportProgress(ImportProgress const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_Int64(v.completed)); r.push_back(encode_Int64(v.total)); r.push_back(encode_String(v.message)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__Optional_Int64_(std::optional<std::int64_t> const& v) { return v ? encode_Int64(*v) : rivet::Value{}; }

inline std::string decode_String(rivet::Value const& v) { if (auto p = std::get_if<std::string>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: String"); }
inline std::int64_t decode_Int64(rivet::Value const& v) { if (auto p = std::get_if<std::int64_t>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Int64"); }
inline TaskStatus decode_TaskStatus(rivet::Value const& v) { auto p = std::get_if<std::string>(&v.data); if (p) { if (*p == "backlog") return TaskStatus::backlog; if (*p == "active") return TaskStatus::active; if (*p == "done") return TaskStatus::done; } throw std::runtime_error("Rivet result type mismatch: TaskStatus"); }
inline BoardTask decode_BoardTask(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 4) throw std::runtime_error("Rivet result type mismatch: BoardTask"); return BoardTask{decode_Int64((*p)[0]), decode_String((*p)[1]), decode_String((*p)[2]), decode_TaskStatus((*p)[3])}; }
inline bool decode_Bool(rivet::Value const& v) { if (auto p = std::get_if<bool>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Bool"); }
inline std::vector<BoardTask> decode__List_BoardTask_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List BoardTask)"); std::vector<BoardTask> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_BoardTask(x)); return r; }
inline std::optional<BoardTask> decode__Optional_BoardTask_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_BoardTask(v); }
inline ImportProgress decode_ImportProgress(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: ImportProgress"); return ImportProgress{decode_Int64((*p)[0]), decode_Int64((*p)[1]), decode_String((*p)[2])}; }
inline std::optional<std::int64_t> decode__Optional_Int64_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_Int64(v); }
}  // namespace detail

struct Operation_progressEvent { ImportProgress value; };
struct Task_savedEvent { BoardTask value; };
using Event = std::variant<Operation_progressEvent, Task_savedEvent>;
inline Event decode_event(std::string const& name, rivet::Value const& value) {
  if (name == "operation-progress") return Event{Operation_progressEvent{detail::decode_ImportProgress(value)}};
  if (name == "task-saved") return Event{Task_savedEvent{detail::decode_BoardTask(value)}};
  throw std::runtime_error("unknown Rivet event: " + name);
}

class API {
 public:
  explicit API(rivet::linux_runtime::Backend& backend) : backend_(backend) {}

  std::future<BoardTask> create_task(std::string title, std::string notes) { auto raw = backend_.call("create-task", rivet::Value::List{detail::encode_String(title), detail::encode_String(notes)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> BoardTask { return detail::decode_BoardTask(raw.get()); }); }
  [[nodiscard]] std::uint64_t create_task_async(std::string title, std::string notes, std::function<void(Result<BoardTask>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("create-task", rivet::Value::List{detail::encode_String(title), detail::encode_String(notes)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<BoardTask> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_BoardTask(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<bool> delete_task(std::int64_t id) { auto raw = backend_.call("delete-task", rivet::Value::List{detail::encode_Int64(id)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> bool { return detail::decode_Bool(raw.get()); }); }
  [[nodiscard]] std::uint64_t delete_task_async(std::int64_t id, std::function<void(Result<bool>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("delete-task", rivet::Value::List{detail::encode_Int64(id)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<bool> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bool(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<BoardTask>> generate_demo_tasks(std::int64_t count) { auto raw = backend_.call("generate-demo-tasks", rivet::Value::List{detail::encode_Int64(count)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<BoardTask> { return detail::decode__List_BoardTask_(raw.get()); }); }
  [[nodiscard]] std::uint64_t generate_demo_tasks_async(std::int64_t count, std::function<void(Result<std::vector<BoardTask>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("generate-demo-tasks", rivet::Value::List{detail::encode_Int64(count)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::vector<BoardTask>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_BoardTask_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::optional<BoardTask>> get_task(std::int64_t id) { auto raw = backend_.call("get-task", rivet::Value::List{detail::encode_Int64(id)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::optional<BoardTask> { return detail::decode__Optional_BoardTask_(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_task_async(std::int64_t id, std::function<void(Result<std::optional<BoardTask>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get-task", rivet::Value::List{detail::encode_Int64(id)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::optional<BoardTask>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__Optional_BoardTask_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<BoardTask>> list_tasks() { auto raw = backend_.call("list-tasks", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<BoardTask> { return detail::decode__List_BoardTask_(raw.get()); }); }
  [[nodiscard]] std::uint64_t list_tasks_async(std::function<void(Result<std::vector<BoardTask>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("list-tasks", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::vector<BoardTask>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_BoardTask_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<BoardTask>> reload_sample_tasks() { auto raw = backend_.call("reload-sample-tasks", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<BoardTask> { return detail::decode__List_BoardTask_(raw.get()); }); }
  [[nodiscard]] std::uint64_t reload_sample_tasks_async(std::function<void(Result<std::vector<BoardTask>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("reload-sample-tasks", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::vector<BoardTask>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_BoardTask_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::optional<BoardTask>> select_task(std::int64_t id) { auto raw = backend_.call("select-task", rivet::Value::List{detail::encode_Int64(id)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::optional<BoardTask> { return detail::decode__Optional_BoardTask_(raw.get()); }); }
  [[nodiscard]] std::uint64_t select_task_async(std::int64_t id, std::function<void(Result<std::optional<BoardTask>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("select-task", rivet::Value::List{detail::encode_Int64(id)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::optional<BoardTask>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__Optional_BoardTask_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<BoardTask> update_task(std::int64_t id, std::string title, std::string notes, TaskStatus status) { auto raw = backend_.call("update-task", rivet::Value::List{detail::encode_Int64(id), detail::encode_String(title), detail::encode_String(notes), detail::encode_TaskStatus(status)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> BoardTask { return detail::decode_BoardTask(raw.get()); }); }
  [[nodiscard]] std::uint64_t update_task_async(std::int64_t id, std::string title, std::string notes, TaskStatus status, std::function<void(Result<BoardTask>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("update-task", rivet::Value::List{detail::encode_Int64(id), detail::encode_String(title), detail::encode_String(notes), detail::encode_TaskStatus(status)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<BoardTask> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_BoardTask(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

  // Shared state
  std::future<std::optional<std::int64_t>> get_selected_task_id() { auto raw = backend_.get_state("selected-task-id"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::optional<std::int64_t> { return detail::decode__Optional_Int64_(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_selected_task_id_async(std::function<void(Result<std::optional<std::int64_t>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("selected-task-id", [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::optional<std::int64_t>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__Optional_Int64_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::optional<std::int64_t>> set_selected_task_id(std::optional<std::int64_t> value) { auto raw = backend_.set_state("selected-task-id", detail::encode__Optional_Int64_(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::optional<std::int64_t> { return detail::decode__Optional_Int64_(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_selected_task_id_async(std::optional<std::int64_t> value, std::function<void(Result<std::optional<std::int64_t>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("selected-task-id", detail::encode__Optional_Int64_(value), [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::optional<std::int64_t>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__Optional_Int64_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<BoardTask>> get_tasks() { auto raw = backend_.get_state("tasks"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<BoardTask> { return detail::decode__List_BoardTask_(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_tasks_async(std::function<void(Result<std::vector<BoardTask>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("tasks", [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::vector<BoardTask>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_BoardTask_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<BoardTask>> set_tasks(std::vector<BoardTask> value) { auto raw = backend_.set_state("tasks", detail::encode__List_BoardTask_(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<BoardTask> { return detail::decode__List_BoardTask_(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_tasks_async(std::vector<BoardTask> value, std::function<void(Result<std::vector<BoardTask>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("tasks", detail::encode__List_BoardTask_(value), [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::vector<BoardTask>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_BoardTask_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

 private:
  rivet::linux_runtime::Backend& backend_;
};

}  // namespace rivet_app
