#lang racket/base

(require rackunit
         "../rivet/private/backend-pending.rkt")

(define (operations table)
  (values (pending-table-id-pending? table)
          (pending-table-admit! table)
          (pending-table-claim! table)
          (pending-table-cancel-action! table)
          (pending-table-begin-state-commit! table)
          (pending-table-end-state-commit! table)
          (pending-table-release! table)
          (pending-table-take-all! table)))

(check-exn exn:fail:contract? (lambda () (make-pending-table 0)))

;; Admission is bounded and duplicate identifiers never replace their owner.
(let ()
  (define table (make-pending-table 1))
  (define-values (pending? admit! claim! cancel! begin! end! release! take-all!)
    (operations table))
  (define first-owner (make-custodian))
  (define other-owner (make-custodian))
  (check-eq? (admit! 7 first-owner) 'admitted)
  (check-eq? (admit! 7 other-owner) 'duplicate)
  (check-eq? (admit! 8 other-owner) 'full)
  (check-true (pending? 7))

  ;; A claim is exactly once and retains capacity until the sender releases it.
  (define request (claim! 7))
  (check-true (pending-request? request))
  (check-eq? (pending-request-custodian request) first-owner)
  (check-false (claim! 7))
  (check-false (cancel! 7))
  (check-eq? (admit! 8 other-owner) 'full)
  (release! 7 request)
  (check-false (pending? 7))
  (check-eq? (admit! 8 other-owner) 'admitted)
  (for ([owner (in-list (take-all!))])
    (custodian-shutdown-all owner)))

;; Cancellation can own the terminal outcome before normal completion.
(let ()
  (define table (make-pending-table 2))
  (define-values (pending? admit! claim! cancel! begin! end! release! take-all!)
    (operations table))
  (define owner (make-custodian))
  (check-eq? (admit! 11 owner) 'admitted)
  (define cancelled (cancel! 11))
  (check-true (pending-request? cancelled))
  (check-false (cancel! 11))
  (check-false (claim! 11))
  (release! 11 cancelled)
  (check-false (pending? 11))
  (custodian-shutdown-all owner))

;; A State commit defers cancellation until the event side effect is admitted,
;; then hands terminal ownership to exactly one cancellation path.
(let ()
  (define table (make-pending-table 1))
  (define-values (pending? admit! claim! cancel! begin! end! release! take-all!)
    (operations table))
  (define owner (make-custodian))
  (check-eq? (admit! 19 owner) 'admitted)
  (define request (begin! 19))
  (check-true (pending-request? request))
  (check-eq? (cancel! 19) 'deferred)
  (check-eq? (cancel! 19) 'deferred)
  (check-eq? (end! 19 request) request)
  (check-false (end! 19 request))
  (check-false (claim! 19))

  ;; Releasing with the wrong identity cannot remove the current request.
  (define wrong-table (make-pending-table 1))
  (define wrong-admit! (pending-table-admit! wrong-table))
  (define wrong-claim! (pending-table-claim! wrong-table))
  (check-eq? (wrong-admit! 19 (make-custodian)) 'admitted)
  (release! 19 (wrong-claim! 19))
  (check-true (pending? 19))
  (release! 19 request)
  (check-false (pending? 19))
  (custodian-shutdown-all owner)
  (for ([remaining-owner (in-list ((pending-table-take-all! wrong-table)))])
    (custodian-shutdown-all remaining-owner)))

;; Shutdown drains every custodian and atomically clears correlation ownership.
(let ()
  (define table (make-pending-table 3))
  (define admit! (pending-table-admit! table))
  (define pending? (pending-table-id-pending? table))
  (define take-all! (pending-table-take-all! table))
  (define owners (for/list ([id '(1 2 3)]) (make-custodian)))
  (for ([id '(1 2 3)] [owner (in-list owners)])
    (check-eq? (admit! id owner) 'admitted))
  (check-equal? (sort (take-all!) < #:key eq-hash-code)
                (sort owners < #:key eq-hash-code))
  (for ([id '(1 2 3)]) (check-false (pending? id)))
  (check-equal? (take-all!) '())
  (for ([owner (in-list owners)]) (custodian-shutdown-all owner)))
