(#hasheq((title . "Review the generated API")
         (notes . "Compare Swift, C++, and Kotlin names produced from one schema.")
         (status . active))
 #hasheq((title . "Check keyboard navigation")
         (notes . "Reach the task list, editor, save, and cancel controls without a pointer.")
         (status . backlog))
 #hasheq((title . "Inspect the packaged app")
         (notes . "Confirm the sample data is present under the staged app resources.")
         (status . backlog)))
