// Generated by Rivet. Do not edit by hand.
import Foundation
import RivetRuntime
import RivetDevice

public enum RivetGeneratedError: Error { case typeMismatch(String); case unknownEvent(String) }
public enum RivetGeneratedConfig {
    public static let moduleName = "backend"
    public static let entryName = "start"
    public static let displayName = "Rivet Taskboard"
    public static let version = "0.1.0"
    public static let build: Int64 = 1
    public static let identifier = "dev.rivet.taskboard"
    public static let releaseChannel = "stable"
}

public enum RivetTypes {
    public enum TaskStatus: String, Codable, Sendable {
        case backlog = "backlog"
        case active = "active"
        case done = "done"
    }

    public struct BoardTask: Codable, Sendable {
        public let id: Int64
        public let title: String
        public let notes: String
        public let status: RivetTypes.TaskStatus
        public init(id: Int64, title: String, notes: String, status: RivetTypes.TaskStatus) {
            self.id = id
            self.title = title
            self.notes = notes
            self.status = status
        }
    }

    public struct ImportProgress: Sendable {
        public let completed: Int64
        public let total: Int64
        public let message: String
        public init(completed: Int64, total: Int64, message: String) {
            self.completed = completed
            self.total = total
            self.message = message
        }
    }

}

private func encode_String(_ v: String) -> RivetValue { .string(v) }
private func encode_Int64(_ v: Int64) -> RivetValue { .int64(v) }
private func encode_TaskStatus(_ v: RivetTypes.TaskStatus) -> RivetValue { .string(v.rawValue) }
private func encode_BoardTask(_ v: RivetTypes.BoardTask) -> RivetValue { .list([encode_Int64(v.id), encode_String(v.title), encode_String(v.notes), encode_TaskStatus(v.status)]) }
private func encode_Bool(_ v: Bool) -> RivetValue { .bool(v) }
private func encode__List_BoardTask_(_ v: [RivetTypes.BoardTask]) -> RivetValue { .list(v.map(encode_BoardTask)) }
private func encode__Optional_BoardTask_(_ v: RivetTypes.BoardTask?) -> RivetValue { v.map(encode_BoardTask) ?? .null }
private func encode_ImportProgress(_ v: RivetTypes.ImportProgress) -> RivetValue { .list([encode_Int64(v.completed), encode_Int64(v.total), encode_String(v.message)]) }
private func encode__Optional_Int64_(_ v: Int64?) -> RivetValue { v.map(encode_Int64) ?? .null }

private func decode_String(_ v: RivetValue) throws -> String { guard case .string(let x) = v else { throw RivetGeneratedError.typeMismatch("String") }; return x }
private func decode_Int64(_ v: RivetValue) throws -> Int64 { guard case .int64(let x) = v else { throw RivetGeneratedError.typeMismatch("Int64") }; return x }
private func decode_TaskStatus(_ v: RivetValue) throws -> RivetTypes.TaskStatus { guard case .string(let x) = v, let result = RivetTypes.TaskStatus(rawValue: x) else { throw RivetGeneratedError.typeMismatch("TaskStatus") }; return result }
private func decode_BoardTask(_ v: RivetValue) throws -> RivetTypes.BoardTask { guard case .list(let xs) = v, xs.count == 4 else { throw RivetGeneratedError.typeMismatch("BoardTask") }; return RivetTypes.BoardTask(id: try decode_Int64(xs[0]), title: try decode_String(xs[1]), notes: try decode_String(xs[2]), status: try decode_TaskStatus(xs[3])) }
private func decode_Bool(_ v: RivetValue) throws -> Bool { guard case .bool(let x) = v else { throw RivetGeneratedError.typeMismatch("Bool") }; return x }
private func decode__List_BoardTask_(_ v: RivetValue) throws -> [RivetTypes.BoardTask] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List BoardTask)") }; return try xs.map(decode_BoardTask) }
private func decode__Optional_BoardTask_(_ v: RivetValue) throws -> RivetTypes.BoardTask? { if case .null = v { return nil }; return try decode_BoardTask(v) }
private func decode_ImportProgress(_ v: RivetValue) throws -> RivetTypes.ImportProgress { guard case .list(let xs) = v, xs.count == 3 else { throw RivetGeneratedError.typeMismatch("ImportProgress") }; return RivetTypes.ImportProgress(completed: try decode_Int64(xs[0]), total: try decode_Int64(xs[1]), message: try decode_String(xs[2])) }
private func decode__Optional_Int64_(_ v: RivetValue) throws -> Int64? { if case .null = v { return nil }; return try decode_Int64(v) }

public enum RivetEvent: Sendable {
    case operation_progress(RivetTypes.ImportProgress)
    case task_saved(RivetTypes.BoardTask)

    public static func decode(name: String, value: RivetValue) throws -> RivetEvent {
        switch name {
        case "operation-progress": return .operation_progress(try decode_ImportProgress(value))
        case "task-saved": return .task_saved(try decode_BoardTask(value))
        default: throw RivetGeneratedError.unknownEvent(name)
        }
    }
}

public struct RivetAPI: Sendable {
    public let client: RivetClient
    public init(client: RivetClient) { self.client = client }

    public func create_task(title: String, notes: String) async throws -> RivetTypes.BoardTask {
        let result = try await client.call("create-task", arguments: [encode_String(title), encode_String(notes)])
        return try decode_BoardTask(result)
    }
    public func delete_task(id: Int64) async throws -> Bool {
        let result = try await client.call("delete-task", arguments: [encode_Int64(id)])
        return try decode_Bool(result)
    }
    public func generate_demo_tasks(count: Int64) async throws -> [RivetTypes.BoardTask] {
        let result = try await client.call("generate-demo-tasks", arguments: [encode_Int64(count)])
        return try decode__List_BoardTask_(result)
    }
    public func get_task(id: Int64) async throws -> RivetTypes.BoardTask? {
        let result = try await client.call("get-task", arguments: [encode_Int64(id)])
        return try decode__Optional_BoardTask_(result)
    }
    public func list_tasks() async throws -> [RivetTypes.BoardTask] {
        let result = try await client.call("list-tasks", arguments: [])
        return try decode__List_BoardTask_(result)
    }
    public func reload_sample_tasks() async throws -> [RivetTypes.BoardTask] {
        let result = try await client.call("reload-sample-tasks", arguments: [])
        return try decode__List_BoardTask_(result)
    }
    public func select_task(id: Int64) async throws -> RivetTypes.BoardTask? {
        let result = try await client.call("select-task", arguments: [encode_Int64(id)])
        return try decode__Optional_BoardTask_(result)
    }
    public func update_task(id: Int64, title: String, notes: String, status: RivetTypes.TaskStatus) async throws -> RivetTypes.BoardTask {
        let result = try await client.call("update-task", arguments: [encode_Int64(id), encode_String(title), encode_String(notes), encode_TaskStatus(status)])
        return try decode_BoardTask(result)
    }

    // Shared state
    public func get_selected_task_id() async throws -> Int64? {
        let result = try await client.getState("selected-task-id")
        return try decode__Optional_Int64_(result)
    }
    @discardableResult
    public func set_selected_task_id(_ value: Int64?) async throws -> Int64? {
        let result = try await client.setState("selected-task-id", value: encode__Optional_Int64_(value))
        return try decode__Optional_Int64_(result)
    }
    public func get_tasks() async throws -> [RivetTypes.BoardTask] {
        let result = try await client.getState("tasks")
        return try decode__List_BoardTask_(result)
    }
    @discardableResult
    public func set_tasks(_ value: [RivetTypes.BoardTask]) async throws -> [RivetTypes.BoardTask] {
        let result = try await client.setState("tasks", value: encode__List_BoardTask_(value))
        return try decode__List_BoardTask_(result)
    }
}

public enum RivetDeviceRequests {
    public struct ListTasks: RivetDeviceRequest {
        public typealias Response = [RivetTypes.BoardTask]
        public static let route = "rpc.list-tasks"
        public init() {
        }
    }
    public struct GetTask: RivetDeviceRequest {
        public typealias Response = RivetTypes.BoardTask?
        public static let route = "rpc.get-task"
        public let id: Int64
        public init(id: Int64) {
            self.id = id
        }
    }
    public struct SelectTask: RivetDeviceRequest {
        public typealias Response = RivetTypes.BoardTask?
        public static let route = "rpc.select-task"
        public let id: Int64
        public init(id: Int64) {
            self.id = id
        }
    }
}

public extension RivetDeviceClient {
    func list_tasks() async throws -> [RivetTypes.BoardTask] {
        try await send(RivetDeviceRequests.ListTasks())
    }
    func get_task(id: Int64) async throws -> RivetTypes.BoardTask? {
        try await send(RivetDeviceRequests.GetTask(id: id))
    }
    func select_task(id: Int64) async throws -> RivetTypes.BoardTask? {
        try await send(RivetDeviceRequests.SelectTask(id: id))
    }
}

public extension RivetDeviceRouter {
    func registerGeneratedBackend(_ api: RivetAPI) throws {
        try register(RivetDeviceRequests.ListTasks.self) { request in
            try await api.list_tasks()
        }
        try register(RivetDeviceRequests.GetTask.self) { request in
            try await api.get_task(id: request.id)
        }
        try register(RivetDeviceRequests.SelectTask.self) { request in
            try await api.select_task(id: request.id)
        }
    }
}
